### ISSUE TITLE
Empty output folder when using --cbz

### ISSUE THREAD

**Issue by videah** [FerrahWolfeh/imageboard-downloader-rs#5]
Running `imageboard_downloader --cbz --pool 6837 -i e621 -o .` leads to all the images being downloaded and an output folder called `e621` created, but once finished the folder is empty with no `.cbz` file to be found

<img width="663" alt="image" src="https://github.com/FerrahWolfeh/imageboard-downloader-rs/assets/4761786/8a32ddc5-3b16-4cc4-9140-655c5e16a009">

**Comment by FerrahWolfeh** [comment]
Now with release `1.5.4` this bug is fixed.
However, without using `-O` to give the exact name of the final cbz file or folder, it will automatically save the pool with its id as file name. Giving the correct name of the pool is out of scope for now, since the file name generation happens way before the extractors are initialized

**Comment by FerrahWolfeh** [comment]
Or `1.5.5` in this case.
fixed an error when using the `-O` flag

**Comment by videah** [comment]
Thank you so much! This tool is now exactly what I need!
